python:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12

clingo:
    - 5.7

pin_run_as_build:
    clingo: x.x

c_stdlib:                       # [osx]
    - macosx_deployment_target  # [osx]
c_stdlib_version:               # [osx]
    - 11.3                      # [osx]
CONDA_BUILD_SYSROOT:            # [osx]
    - /opt/MacOSX11.3.sdk       # [osx]
