python:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12

clingo:
    - 5.7

pin_run_as_build:
    clingo: x.x

MACOSX_DEPLOYMENT_TARGET: 10.15  # [osx and not arm64]
MACOSX_DEPLOYMENT_TARGET: 11.3   # [osx and arm64]
CONDA_BUILD_SYSROOT:             # [osx]
    - /opt/MacOSX10.15.sdk       # [osx and not arm64]
    - /opt/MacOSX11.3.sdk        # [osx and arm64]
