python:
    - 3.8
    - 3.9
    - 3.10
    - 3.11
    - 3.12

clingo:
    - 5.7

pin_run_as_build:
    clingo: x.x

MACOSX_DEPLOYMENT_TARGET: 10.15  # [osx]
CONDA_BUILD_SYSROOT:             # [osx]
    - /opt/MacOSX10.15.sdk       # [osx]
