fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        exclude: _clingodl.c
        args: ["-i"]
      - id: clang-tidy
        exclude: _clingodl.c
        args: ["-fix"]
